### ISSUE TITLE
flipNormal()

### ISSUE THREAD

**Issue by ereator** [Project-10/OpenRT#35]
By default when creating a geometric object, its normals point outward of the object. For some cases it is useful to force the normals to point inside the object. Thus there is a need for a `void flipNormals(void)` method.

**Comment by ereator** [comment]
Hi @otmanesabir 
- One open question here if the method `void flipNormals(void)` belongs to the geometry or to shading. _I.e._ if it should be implemented in the interface class `IPrim` or in class `CShader`
- My initial idea was to implement it as a part of geometry, _i.e._  as `void IPrim::flipNormals(void) { m_flipNormals = !m_flipNormals; }`, where `bool m_flipNormals = false;` is a private member-variable of the interface class `IPrim`. Then the implementation of the `getNormal()` methods would look like 
```
// calculate normal
return m_flipNormals ? -normal : normal;
```
- Such idea would require that all the methods `getNormal()` should be modified. To prevent that, maybe it makes sense to do a _dependency injection_ trick, but I am also not sure if it is a good idea. The trick itself is the following:
  - Change method `virtual Vec3f IPrim::getNormal(const Ray& ray) const = 0;` to `Vec3f IPrim::getNormal(const Ray& ray) const { return m_flipNormals ? -doGetNormal(ray) : doGetNormal(ray);  }`
  - add protected or private method `virtual Vec3f IPrim::doGetNormal(const Ray& ray) const = 0;`
  - rename all the `getNormal()` methods in derived from `IPrim` classes to `doGetNormal()`

**Comment by otmanesabir** [comment]
Hi @ereator 

Thank you very much for inviting me to contribute to this topic.

I believe that it probably makes more sense to do this in the geometry domain, as I don't think a shader should be able to modify the geometry but instead only make the decision of how to render it. This would be the preferred way in my opinion.

* As for the approach, I very much like the idea of not having to modify every `getNormal()` method in every class and probably also not relying on contributors memory to always make sure they perform this check and return the flipped normal if true when introducing new geometries.

I also think this DI method is a solid approach but initially, when I first thought of this, I had the following approach in mind:
* create a `m_normal` private variable in the `IPrim` abstract classes.
* add a setter, getter members which are both not virtual methods. (the same way we currently do with `m_name`)
* make every implementing class use this setter instead of having its own `m_normal`. (this also has the benefit of refactoring a variable used across all geometric primitives to the central abstract class).
* then implement `IPrim::flipNormals()` using these methods.

In this case, it would also not be necessary to introduce `m_flipNormals`? Though I see its clear advantages in debugging and simplicity, I also think it could make the primitive geometries a little bigger than they ought to be.

**Comment by otmanesabir** [comment]
Something to note:

After having a look, I realized that our `getNormal()` is currently parametrized. However, out of all the primitives, only the `PrimSphere` currently utilizes this parameter. So if we are to go with the solution I suggested, this would be an extra problem we have to consider. So this is a pro of the DI injection method.

**Comment by ereator** [comment]
Yes, in general, the `getNormal()` method depends on the point where exactly the ray hits the surface. Thus, even if organize `getNormal()` as a non-virtual getter, somewhere there we will need to call probably `calculateNormal()` `or doGetNormal()` to fill `m_normal` and then return it.

One more important point, I have forgotten to mention. Recently I have added also `virtual Vec3f IPrim::getShadingNormal(const Ray& ray)`. I had to split old getNormal()  into 2 methods: `getNormal()` and `getShadingNormal()` to fight one problem with shading artifacts for surfaces, where the normal is interpolated. For inverting normals, this new methods should be also taken into consideration.
